name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
        with:
          go-version: "1.25.4"

      - name: Verify dependencies
        run: |
          go mod verify
          go mod tidy -v

      - name: Go vet
        run: go vet ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@6be2b51fd78feca86af91f5186b7964d76cb1256
        env:
          GOSECGOVERSION: "go1.25.4"
          GOTOOLCHAIN: auto
        with:
          args: ./...

      - name: Run govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee
        with:
          go-version-input: "1.25.4"
          go-package: ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -coverpkg=. -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
