name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Explicitly declare permissions to address token-permissions security issue
permissions:
  contents: read

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@d65369c3fd1c3e4d3bff8c7912cc6255ddce665a
        with:
          version: v2.0.0
          args: --timeout=5m --config=_lint/.production.golangci.json 
